version: '2'

services:

  mysql:
    image: mysql:8
    restart: unless-stopped
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    networks:
      - oc
    environment:
      - MYSQL_ROOT_PASSWORD=1975
      - MYSQL_DATABASE=mediscreendb
    ports:
      - 3307:3306


  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    volumes:
    - ./init/:/data/db
    networks:
      - oc
    ports:
      - 27017:27017

  mediscreen:
    image: mediscreen:1.0.10
    networks:
      - oc
    depends_on:
      - mysql
    ports:
      - "8081:8081"

  mediscreennote:
    image: mediscreennote:1.0.10
    networks:
      - oc
    depends_on:
      - mongo_db
    ports:
      - "8082:8082"

  mediscreen-diabete:
    image: mediscreendiabete:1.0.10
    ports:
      - "8080:8080"

    networks:
      - oc
    depends_on:
      - mediscreen
      - mediscreennote
      

networks:
  oc:
    driver: bridge